name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - pip=23.3.1
  - requests=2.24.0
  - pyarrow
  - pandas
  - cmake
  - ninja
  - anyio==4.6.2.post1
  - appdirs==1.4.4
  - argon2-cffi==23.1.0
  - attrs==24.2.0
  - babel==2.14.0
  - bleach==6.2.0
  - blinker==1.8.2
  - brotli==1.1.0
  - certifi==2024.8.30
  - cffi==1.17.1
  - charset-normalizer==3.4.0
  - click==8.1.7
  - cloudpickle==2.2.1
  - contourpy==1.3.0
  - cryptography
  - decorator==5.1.1
  - defusedxml==0.7.1
  - entrypoints==0.4
  - fastjsonschema==2.20.0
  - fonttools==4.54.1
  - gitdb==4.0.11
  - gitpython==3.1.43
  - greenlet==3.1.1
  - h2==4.1.0
  - hpack==4.0.0
  - idna==3.10
  - importlib-metadata==6.11.0
  - importlib-resources==6.4.5
  - itsdangerous==2.2.0
  - jedi==0.19.1
  - jinja2==3.1.4
  - joblib==1.4.2
  - jsonschema==4.23.0
  - jupyter-client==8.6.3
  - jupyter-core==5.7.2
  - jupyterlab==4.0.9
  - kiwisolver==1.4.7
  - matplotlib==3.6.3
  - nbconvert==7.16.4
  - nbformat==5.10.4
  - nest-asyncio==1.6.0
  - numpy==1.23.5
  - oauthlib==3.2.2
  - omegaconf==2.3.0
  - packaging==23.2
  - pandas-profiling==3.6.2
  - pillow==11.0.0
  - prompt-toolkit==3.0.48
  - protobuf==4.25.5
  - psutil==6.1.0
  - ptyprocess==0.7.0
  - pyjwt==2.9.0
  - pyparsing==3.2.0
  - python-dateutil==2.9.0
  - pyyaml==6.0.2
  - pyzmq==26.2.0
  - requests==2.28.2
  - scikit-learn==1.5.2
  - scipy==1.9.3
  - seaborn==0.12.2
  - send2trash==1.8.3
  - setuptools==75.3.0
  - six==1.16.0
  - sniffio==1.3.1
  - soupsieve==2.5
  - sqlalchemy==2.0.36
  - statsmodels==0.13.5
  - terminado==0.18.1
  - threadpoolctl==3.5.0
  - tinycss2==1.4.0
  - toml==0.10.2
  - tornado==6.4.1
  - tqdm==4.64.1
  - traitlets==5.14.3
  - typing-extensions==4.12.2
  - typing-utils==0.1.0
  - tzdata==2024.2
  - urllib3==1.26.20
  - visions==0.7.5
  - wcwidth==0.2.13
  - werkzeug==3.1.1
  - wheel==0.44.0
  - zipp==3.20.2
  - zstandard==0.23.0
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
      - git+https://github.com/udacity/Project-Build-an-ML-Pipeline-Starter.git#egg=wandb-utils&subdirectory=components
      - alembic==1.13.3
      - antlr4-python3-runtime==4.9.3
      - asttokens==2.4.1
      - autocommand==2.2.2
      - backports.tarfile==1.2.0
      - beautifulsoup4==4.12.3
      - docker==6.1.3
      - docker-pycreds==0.4.0
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - flask==3.0.3
      - fqdn==1.5.1
      - gunicorn==21.2.0
      - htmlmin==0.1.12
      - hydra-core==1.3.2
      - hyperframe==6.0.1
      - imagehash==4.3.1
      - inflect==7.3.1
      - ipykernel==6.29.5
      - ipython==8.29.0
      - isoduration==20.11.0
      - jaraco.collections==5.1.0
      - jaraco.context==5.3.0
      - jaraco.functools==4.0.1
      - jaraco.text==3.12.1
      - json5==0.9.25
      - jsonpointer==3.0.0
      - jsonschema-specifications==2024.10.1
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server-terminals==0.5.3
      - jupyter-server==2.14.2
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - mako==1.3.6
      - markdown==3.7
      - markupsafe==3.0.2
      - matplotlib-inline==0.1.7
      - mistune==3.0.2
      - more-itertools==10.3.0
      - multimethod==1.9.1
      - munkres==1.1.4
      - nbclient==0.10.0
      - networkx==3.4.2
      - notebook-shim==0.2.4
      - parso==0.8.4
      - patsy==0.5.6
      - pexpect==4.9.0
      - phik==0.12.4
      - pickleshare==0.7.5
      - platformdirs==4.3.6
      - ply==3.11
      - prometheus-client==0.21.0
      - pure-eval==0.2.3
      - pydantic==1.10.18
      - pygments==2.18.0
      - pyqt5==5.15.9
      - pyqt5-sip==12.12.2
      - pycparser==2.22
      - pywavelets==1.7.0
      - querystring-parser==1.2.4
      - referencing==0.35.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.20.1
      - sentry-sdk==2.17.0
      - setproctitle==1.3.3
      - sip==6.7.12
      - smmap==5.0.1
      - sqlparse==0.5.1
      - stack-data==0.6.2
      - tabulate==0.9.0
      - tangled-up-in-unicode==0.2.0
      - typeguard==2.13.3
      - types-python-dateutil==2.9.0.20241003
      - unicodedata2==15.1.0
      - uri-template==1.3.0
      - webcolors==24.8.0
      - webencodings==0.5.1
      - websocket-client==1.8.0